LibraryApp/Models/Data_Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryApp.Models.Data_Models
{
    public class Article
    {
        public int ArticleId { get; set; }

        public string ArticleName { get; set; }

        public string PublicationDate { get; set; }

        public string ArticleText { get; set; }
    }
}

LibraryApp/Models/Data_Models/DBWorker.cs
using LibraryApp.Models.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryApp.Models.Data_Models
{
    public class DBWorker
    {
        public Articles GetArticles()
        {
            using (var db = new LibraryContext())
            {
                var query = db.Articles.Select(x => x).ToList();
                var articles = new Articles(query);

                return articles;
            }
        }

        public Reports GetReports()
        {
            using (var db = new LibraryContext())
            {
                var query = db.Reports.Select(x => x).ToList();
                var reports = new Reports(query);

                return reports;
            }
        }
        public void AddReport(Report report)
        {
            using (var db = new LibraryContext())
            {
                db.Reports.Add(report);
                db.SaveChanges();
            }
        }

        public void AddQuestionary(Questionary questionary)
        {
            using (var db = new LibraryContext())
            {
                db.Questionaries.Add(questionary);
                db.SaveChanges();
            }
        }
    }
}

LibraryApp/Models/Data_Models/LibraryContext.cs
namespace LibraryApp.Models.Data_Models
{
    using System;
    using System.Data.Entity;
    using System.Linq;

    public class LibraryContext : DbContext
    {
        public LibraryContext()
            : base("name=LibraryContext")
        {
        }

        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Questionary> Questionaries { get; set; }
    }
}

LibraryApp/Models/Data_Models/Questionary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LibraryApp.Models.Data_Models
{
    public class Questionary
    {
        public int QuestionaryId { get; set; }

        [Required(ErrorMessage = "Enter User email")]
        [StringLength(25, MinimumLength = 3)]
        public string UserEmail { get; set; }

        [Required(ErrorMessage = "Enter User name")]
        [StringLength(25, MinimumLength = 3)]
        public string UserName { get; set; }
        
        public string HTML { get; set; }
        
        public string CSS { get; set; }
        
        public string JS { get; set; }
        
        public string Gender { get; set; }
    }
}

LibraryApp/Models/Data_Models/Report.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LibraryApp.Models.Data_Models
{
    public class Report
    {
        public int ReportId { get; set; }
        public string AuthorName { get; set; }
        public string Date { get; set; }
        
        public string ReportText { get; set; }

    }
}

LibraryApp/Models/View_Models/Articles.cs
using LibraryApp.Models.Data_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryApp.Models.View_Models
{
    public class Articles
    {
        public ICollection<Article> List { get; set; }

        public Articles()
        {
            List = new List<Article>();
        }

        public Articles(ICollection<Article> newList)
        {
            List = newList;
        }


    }
}

LibraryApp/Models/View_Models/Reports.cs
using LibraryApp.Models.Data_Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LibraryApp.Models.View_Models
{
    public class Reports
    {
        public ICollection<Report> List { get; set; }

        public Reports()
        {
            List = new List<Report>();
        }

        public Reports(ICollection<Report> newList)
        {
            List = newList;
        }
     
        public Report this[int i]
        {
            get => List.ElementAt(i);

            set => List.Add(value);
        }
    }
}

LibraryApp/Controllers/GuestPageController.cs
using LibraryApp.Models;
using LibraryApp.Models.Data_Models;
using LibraryApp.Models.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class GuestPageController : Controller
    {
        // GET: GuestPage
        public ActionResult Index()
        {
            var dbWorker = new DBWorker();
            var reports = dbWorker.GetReports();

            return View("Index", reports);
        }

        [HttpPost]
        public ActionResult AddReport(string authorName, string reportText )
        {   
            if (String.IsNullOrEmpty(authorName))
                ModelState.AddModelError("authorName", "Please enter your name");

            if (String.IsNullOrEmpty(reportText))
                ModelState.AddModelError("reportText", "Please enter report text");

            var dbWorker = new DBWorker();

            if (ModelState.IsValid)
            {   
                Report report = new Report() { AuthorName = authorName, ReportText = reportText, Date = DateTime.Now.ToString() };  
                dbWorker.AddReport(report);
            }

            var reports = dbWorker.GetReports();

            return View("Index", reports);
        }
    }
}

LibraryApp/Controllers/MainPageController.cs
using LibraryApp.Models;
using LibraryApp.Models.Data_Models;
using LibraryApp.Models.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class MainPageController : Controller
    {
        // GET: MainPage
        public ActionResult Index()
        {
            var dbWorker = new DBWorker();
            var articles = dbWorker.GetArticles();

            return View("Index", articles);
                
        }
    }
}

LibraryApp/Controllers/QuestionaryController.cs
using LibraryApp.Models.Data_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class QuestionaryController : Controller
    {
        // GET: Questionary
        public ActionResult Index()
        {
            return View("Index");
        }
        
        [HttpPost]
        public ActionResult Index(Questionary questionary )
        {
            if (questionary.JS != "true" && questionary.HTML != "true" && questionary.CSS != "true")
                ModelState.AddModelError("", "You have not enough skills (at least 1)");

            if (ModelState.IsValid)
            {
                var dbWorker = new DBWorker();
                dbWorker.AddQuestionary(questionary);

                return View("QuestionaryResult", questionary);
            }
            else
                return View();
        }
    }
}

LibraryApp/Views/GuestPage/Index.cshtml
@model LibraryApp.Models.View_Models.Reports


@{
    ViewBag.Title = "GuestPage";

}

@using (Html.BeginForm("AddReport", "GuestPage", FormMethod.Post))
{
        @Html.ValidationSummary()
    <p>
        Authors name:
        @Html.TextBox("AuthorName")
    </p>
    <p>
        Report text:
        @Html.TextBox("ReportText")
    </p>

    <input type="submit" name="Button" value="Submit" />
}

@foreach (var report in Model.List)
{
    <div class="article">
        @report.AuthorName
        <br />@report.Date
        <br />@report.ReportText
    </div>
}

LibraryApp/Views/MainPage/Index.cshtml
@model LibraryApp.Models.View_Models.Articles

@{
    ViewBag.Title = "Index";
}

@foreach (var element in Model.List)
{
    <div class="article">
        Назва: @element.ArticleName
        <br />
        Дата публікації: @element.PublicationDate
        <br />
        Текст: @element.ArticleText
        <br />
    </div>
}

LibraryApp/Views/Questionary/Index.cshtml
@model LibraryApp.Models.Data_Models.Questionary
@{
    ViewBag.Title = "Questionary";
}
@using LibraryApp.CustomHelpers

@helper CreateQuestionary()//low level
    {
        using (Html.BeginForm("Index", "Questionary", FormMethod.Post))
        {   
            @Html.ValidationSummary(true)
            <div style="margin:5px; width:100%;">
                <p style="width: 80vw">@Html.ValidationMessageFor(m => m.UserEmail)</p>
                @Html.TextBox("UserEmail", null, new { placeholder = "Enter your Email", style = " width:200px" })
                <br />
                <p style="width: 80vw">@Html.ValidationMessageFor(m => m.UserName)</p>
                @Html.TextBox("UserName", null, new { placeholder = "Enter your Name", style = " width:200px" })
                <br />
                <span>Skills:</span>
                <br />
                <div id = "skills" style="display:grid; grid-template-columns: 50px 50px; margin-left:40px; width: 100px">
                    @Html.CheckBox("HTML", false)
                    <span>HTML</span>

                    @Html.CheckBox("CSS", false)
                    <span>CSS</span>

                    @Html.CheckBox("JS", false)
                    <span>JS</span>
                </div>
                <br />
                <span>Gender:</span>
                <br />
                <ul style="margin-left:25px; width: 100px">
                    <li>
                        @Html.RadioButton("Gender", "Male", true)
                        <span>Male</span>
                    </li>
                    <li>
                        @Html.RadioButton("Gender", "Female")
                        <span>Female</span>
                    </li>
                </ul>
                <input type="submit" name="Button" value="Submit" />
            </div>
        }
    }

@CreateQuestionary()

@*@Html.CreateQuestionary()*@ @*middle*@

@*@helper CreateQustionaryInlineAndExtensionMethod()// advanced
{
    <div style="border: 1px solid red; border-radius: 5px">
        @Html.CreateQuestionary()
    </div>
}

@CreateQustionaryInlineAndExtensionMethod()*@

LibraryApp/Views/Questionary/QuestionaryResult.cshtml
@model LibraryApp.Models.Data_Models.Questionary
@{
    ViewBag.Title = "QuestionaryResult";
}

    <div style="margin:5px">
        <span>User email: </span>@Model.UserEmail
        <br />
        <span>User name: </span>@Model.UserName
        <br />
        <span>Skills:</span>
        <ul style="margin-left:25px; width: 100px">
            @if (@Model.HTML == "on" || @Model.HTML == "true") 
            {
                <li><span>HTML</span></li>
            }
            @if (@Model.CSS == "on" || @Model.CSS == "true")
            {
                <li><span>CSS</span></li>
            }
            @if (@Model.JS == "on" || @Model.JS == "true")
            {
                <li><span>JS</span></li>
            }
        </ul>
        <span>Gender:</span>
        @Model.Gender
    </div>

LibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LibraryApp/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Library.css")

</head>
<div class="header">
    <div id="logo"></div>
    <div id="site-name">Site-Name</div>
</div>

<body>
    </div>
    <div class="body-container">
        <div class="body-element" id="Main-body">
            @RenderBody()
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/jqueryval")
            @RenderSection("Scripts", required: false)
        </div>
        <div class="body-element" id="Menu">
            @Html.ActionLink("Main", "Index", "MainPage")
            <br />@Html.ActionLink("Guest", "Index", "GuestPage")
            <br />@Html.ActionLink("Questionary", "Index", "Questionary")
        </div>
        <hr />
    </div>
</body>

<div class="footer">
    <p>Taras Trush | tarastaras144@gmail.com</p>
    <a href="#top">Jump to top of page</a>
</div>
</html>